# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - master	  
      - feature/*
  paths:
    exclude:
      - 'WeatherApiOne/*'
      - 'WeatherApiTwo/*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: |
    echo "Echo from '/' root folder"


