# Build numbering format
name: $(BuildID)

trigger:
  branches:
    # More on paths: https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#paths
    include:
      - master	  
      - feature/*
      #- refs/tags/{tagname}
    exclude:
        - refs/tags/ignoreme
        - README.md
  paths:
    include:
      - 'WeatherApiShared/*' 
    exclude:
      - 'WeatherApiOne/*'
      - 'WeatherApiTwo/*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: |
    echo "Echo from '/' root folder"


